### ISSUE TITLE
Tasks to do Back End

### ISSUE THREAD

**Issue by ozzysp** [ozzysp/AlphaCopy#3]
Back-End Road Map

- [x]  - Init App

- [ ]  - First display shows "Greetings"

- [ ]  - Check connected devices on USB ports

- [ ]  - Second display shows "Loading devices''
 
- [ ]  - First block "IF" checks if SD and HDD has found if not scan ports again

- [ ]  - Third display shows "Found 2 Devices"

- [ ]  - Fourth display shows "Copy from SD"

- [ ]  - Fifth display shows "Destination HD"

- [ ]  - Sixth display shows "Make New Dir"

- [ ]  - Seventh display shows "Start Copy"

- [ ]  - Make new dir with sequential number on new folder

- [ ]  - Copy all from SD Card

- [ ]  - Check hash from each file to confirm integrity of files

- [ ]  - Eighth display shows "Progress Bar" 

- [ ]  - Second block "IF" check if copy has reached successfully transfer to new directory

- [ ]  - Ninth display shows "Done Errors" if copy has failures

- [ ]  - Tenth display shows "Done" if copy has successful 

- [ ]  - Eleventh display shows "Eject Devices"

- [ ]  - Twelfth display shows "Make New Copy (SD Card has ejected)" 

- [ ]  - Thirteenth display shows "Scan New Devices" - Return to second item - Check connected devices on USB ports

**Comment by mathssantos** [comment]
- [ ]  - Check Memory Devices
