### ISSUE TITLE
Upgrade copy function

### ISSUE THREAD

**Issue by ozzysp** [ozzysp/AlphaCopy#5]
Alphacopy/copy_function only works with texts. We need upgrade to copy any kind of files.

**Comment by edinhodiluviano** [comment]
Was fixed with [PR#8](https://github.com/ozzysp/AlphaCopy/pull/8): [feat(copy): can copy text and images ](https://github.com/ozzysp/AlphaCopy/pull/8/commits/ce204f5b81bfab5a346951adee3de94fddaf0b58)

**Comment by ozzysp** [comment]
Well done, Edinho! Let's go to next step!
